name: Deploy

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  pr_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: Setup NODE
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Installing npm dependencies
        run: |
          npm i
          npm i -g prettier

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: "{{ secret.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "{{ secret.AWS_ACCESS_KEY }}"
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
        run: terraform apply -auto-approve -var="access_key=${ACCESS_KEY}" -var="access_secret=${ACCESS_SECRET}"
